apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-engine-vars
  namespace: {{ .Values.namespace | default "accuknox-agents" }}
data:
  {{- range $k, $v := .Values.feederService.discoveryEngineVars }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote -}}
  {{- else }}
  {{ $k }}:  ""
  {{- end }}
  {{- end }} 