apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "rafay-datadog.labels" . | nindent 4 }}
data:
  config.ini: |-
    [rafay]
    url = {{ .Values.config.url }}
    ops_console_url = {{ .Values.config.ops_console_url | default .Values.config.url }}
    filter = {{ .Values.config.filter }}
    interval = {{ .Values.config.interval }}
    ssl_verify = {{ .Values.config.ssl_verify }}

    [Datadog]
    host = {{ .Values.config.host }}
