{{- if eq .Values.config.secret_name "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "rafay-datadog.labels" . | nindent 4 }}
type: Opaque
data:
  apikey: {{ .Values.config.apikey | b64enc }}
  apisecret: {{ .Values.config.apisecret | b64enc }}
  token: {{ .Values.config.datadogkey | b64enc }}
{{- end -}}