annotations:
  category: LogManagement
apiVersion: v2
appVersion: "1.0"
description: Aggregate and stream your organization's audit logs to syslog
name: rafay-syslog
type: application
version: "1.0"
home: https://github.com/RafaySystems/rafay-helm-charts/tree/main/charts/rafay-syslog
icon: https://rafay-partner-logos.s3.us-west-1.amazonaws.com/rafay-charts-logo.png
