{{- if eq .Values.config.secret_name "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "rafay-elasticsearch.labels" . | nindent 4 }}
type: Opaque
data:
  rafaykey: {{ .Values.config.rafay_api_key | b64enc }}
  eskey: {{ .Values.config.es_api_key | b64enc }}
  esuser: {{ .Values.config.es_username | b64enc }}
  espassword: {{ .Values.config.es_password | b64enc }}
{{- end -}}