apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "rafay-syslog.labels" . | nindent 4 }}
data:
  config.ini: |-
    [rafay]
    url = {{ .Values.config.url }}
    filter = {{ .Values.config.filter }}
    interval = {{ .Values.config.interval }}
    
    [syslog]
    host = {{ .Values.config.host }}
    port = {{ .Values.config.port }}
    ssl_verify = {{ .Values.config.ssl_verify }}
