{{- if eq .Values.config.secret_name "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "rafay-syslog.labels" . | nindent 4 }}
type: Opaque
data:
  rafaykey: {{ .Values.config.rafay_api_key | b64enc }}
  rafaysecret: {{ .Values.config.rafay_api_secret | b64enc }}
{{- end -}}