{{- if .Values.global.Rafay.openshift }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: rafay-privileged-scc
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
    release.openshift.io/create-only: "true"
  labels:
    rep-workload: "rafay-privileged-scc"
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:nodes
- system:masters
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:rafay-system:default
- system:serviceaccount:rafay-system:system-sa
- system:serviceaccount:rafay-system:ingress-controller-v1
- system:serviceaccount:rafay-system:ingress-controller-v1-admission
- system:serviceaccount:rafay-system:ingress-controller-v0
- system:serviceaccount:rafay-system:ingress-controller-v0-admission
- system:serviceaccount:rafay-system:gatekeeper-admin
- system:serviceaccount:rafay-system:gatekeeper-update-namespace-label
- system:serviceaccount:rafay-infra:rafay-prometheus-adapter
- system:serviceaccount:rafay-infra:rafay-prometheus-alertmanager
- system:serviceaccount:rafay-infra:rafay-prometheus-helm-exporter
- system:serviceaccount:rafay-infra:rafay-prometheus-kube-state-metrics
- system:serviceaccount:rafay-infra:rafay-prometheus-metrics-server
- system:serviceaccount:rafay-infra:rafay-prometheus-server
- system:serviceaccount:rafay-infra:default
- system:serviceaccount:rafay-infra:system-sa
- system:serviceaccount:rafay-infra:rafay-prometheus-node-exporter
volumes:
- '*'
{{- end }}
