apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2-relay-agent
  namespace: rafay-system
  labels:
    app: v2-relay-agent
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: v2-infra
    meta.helm.sh/release-namespace: rafay-system
spec:
  selector:
    matchLabels:
      app: v2-relay-agent
  replicas: 1
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: v2-relay-agent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      priorityClassName: rafay-cluster-critical-v3
      serviceAccountName: system-sa
      terminationGracePeriodSeconds: 200
      initContainers:
        - name: set-limits
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag}}"
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: relay-agent
          image: "{{ .Values.relay.image.repository }}:{{ .Values.relay.image.tag}}"
          imagePullPolicy: {{ .Values.relay.image.pullPolicy }}
          args: ["--mode=client", "--log-level=3"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MAX_DIALS
              valueFrom:
                configMapKeyRef:
                  name: v2-relay-agent-config
                  key: maxDials
                  optional: true
            - name: DIALOUT_PROXY
              valueFrom:
                configMapKeyRef:
                  name: proxy-config-v3
                  key: httpsProxy
                  optional: true
            - name: DIALOUT_PROXY_AUTHENTICATION
              valueFrom:
                configMapKeyRef:
                  name: proxy-config-v3
                  key: proxyAuth
                  optional: true
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: proxy-config-v3
                  key: httpProxy
                  optional: true
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: proxy-config-v3
                  key: httpsProxy
                  optional: true
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  name: proxy-config-v3
                  key: noProxy
                  optional: true
            - name: BOOTSTRAP_CA_CERT
              valueFrom:
                configMapKeyRef:
                  name: proxy-config-v3
                  key: bootstrapCA
                  optional: true
            - name: ALLOW_INSECURE_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: proxy-config-v3
                  key: allowInsecureBootstrap
                  optional: true      
          volumeMounts:
            - name: v2-relay-agent-config
              mountPath: /etc/config
          resources:
            requests:
              cpu: {{ .Values.relay.resources.requests.cpu }}
              memory: {{ .Values.relay.resources.requests.memory }}
            limits:
              cpu: {{ .Values.relay.resources.limits.cpu }}
              memory: {{ .Values.relay.resources.limits.memory }}
      volumes:
        - name: v2-relay-agent-config
          configMap:
            name: v2-relay-agent-config
