{{- if eq (include "condition" .) "false" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "discoveryEngine.name" . }}
  namespace: {{ .Values.namespace | default "accuknox-agents" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "discoveryEngine.name" . }}
rules:
- apiGroups: ["*"]
  resources: ["pods", "services", "deployments", "endpoints", "namespaces", "nodes", "replicasets", "statefulsets", "daemonsets", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "discoveryEngine.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "discoveryEngine.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "discoveryEngine.name" . }}
  namespace: {{ .Values.namespace | default "accuknox-agents" }}
{{- end }}  