apiVersion: v1
kind: Service
metadata:
  name: {{ include "discoveryEngine.name" . }}
  labels:
    app: {{ include "discoveryEngine.name" . }}
spec:
  ports:
  - port: 9089
    targetPort: 9089
    protocol: TCP
  selector:
    app: {{ include "discoveryEngine.name" . }}