annotations:
  charts.openshift.io/name: rafay-operator-redhat
apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
kubeVersion: '>= 1.20.0-0'
name: rafay-operator-redhat
type: application
version: 0.2.0
