# Default values for v2-infra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  Rafay: {}

connector:
  image:
    repository: registry.rafay-edge.net/rafay/rafay-connector-redhat 
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: r1.22.1

controller:
  image:
    repository: registry.rafay-edge.net/rafay/cluster-controller-redhat
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: r1.22.1

token: "ced2s9c0fga0i1d6sruf0"
api_addr: api.rafay.dev 
control_addr: control.rafay.dev
allow_insecure_bootstrap: ""
http_proxy: ""
https_proxy: ""
no_proxy: ""
proxy_auth: ""
openshift: true
