apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "rafay-cloudwatch.labels" . | nindent 4 }}
data:
  config.ini: |-
    [rafay]
    url = {{ .Values.config.url }}
    initialFilter = {{ .Values.config.filter }}
    interval = {{ .Values.config.interval }}
    
    [CloudWatch]
    createStreams = {{ .Values.config.createLogStreams }}
    logGroup = {{ .Values.config.logGroup }}
    auditLogStream = {{ .Values.config.auditLogStream }}
    kubectlLogStream = {{ .Values.config.kubectlLogStream }}
    opaLogStream = {{ .Values.config.opaLogStream }}
