{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-rolebinding
  labels:
    {{- include "rafay-cloudwatch.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
  {{- if .Values.serviceAccount.create }}
    name: {{ .Release.Name }}-serviceaccount
  {{- else }}
    name: {{ .Values.serviceAccount.name }}
  {{- end }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
