apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rafay:rafay-system:proxy-rolebinding
  namespace: rafay-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rafay:proxy-role
subjects:
- kind: ServiceAccount
  name: system-sa
  namespace: rafay-system
- kind: ServiceAccount
  name: default
  namespace: rafay-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rafay:rafay-system:manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rafay:manager
subjects:
- kind: ServiceAccount
  name: system-sa
  namespace: rafay-system
- kind: ServiceAccount
  name: default
  namespace: rafay-system
