apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
        name: rafay:proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
        name: rafay:manager
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cluster.rafay.dev
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.rafay.dev
  resources:
  - namespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.rafay.dev
  resources:
  - tasklets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.rafay.dev
  resources:
  - tasklets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.rafay.dev
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.rafay.dev
  resources:
  - tasks/status
  verbs:
  - get
  - patch
  - update
