apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: v2-infra
    meta.helm.sh/release-namespace: rafay-system
  labels:
    app.kubernetes.io/managed-by: Helm
    control-plane: controller-manager-v3
  name: controller-manager-v3
  namespace: rafay-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager-v3
  template:
    metadata:
      labels:
        control-plane: controller-manager-v3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag}}"
        name: manager
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi
      priorityClassName: rafay-cluster-critical
      serviceAccountName: system-sa
      terminationGracePeriodSeconds: 10
