apiVersion: scheduling.k8s.io/v1
description: This priority class should be used for rafay service pods only.
kind: PriorityClass
metadata:
  name: rafay-cluster-critical
value: 1000000000
---
apiVersion: scheduling.k8s.io/v1
description: This priority class should be used for rafay service pods only.
kind: PriorityClass
metadata:
  annotations:
    meta.helm.sh/release-name: v2-infra
    meta.helm.sh/release-namespace: rafay-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: rafay-cluster-critical-v3
value: 1000000000