apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rafay:leader-election-rolebinding
  namespace: rafay-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rafay:leader-election-role
subjects:
- kind: ServiceAccount
  name: system-sa
  namespace: rafay-system
- kind: ServiceAccount
  name: default
  namespace: rafay-system
