{{- if eq (include "condition" .) "false" }}
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "policyEnforcementAgent.name" . }}
  namespace: {{ .Values.namespace | default "accuknox-agents" }} 
data:
  application.yaml: |-
    endpoint:
      urlendpoint: /pps/api/v1/policy-provider/fetch-policy
      baseurlendpoint: https://{{ .Values.ppsHost | default "pps.accuknox.com" }}

    statusendpoint:
      endpoint: https://{{ .Values.ppsHost | default "pps.accuknox.com" }}/pps/api/v1/policy-provider/change-status-policy
      
    secret:
      key2: 511dfbdb941561cbea02ffaf1043df6b47512e01f75d5ae5932cd9a36b4f07c0

    syncuptime:
      t: 5

    annotation:
      statusendpoint: /pps/api/v1/policy-provider/update-annotation-status
      annotationendpoint: /pps/api/v1/policy-provider/fetch-annotations
      basepath: https://{{ .Values.ppsHost | default "pps.accuknox.com" }}

    spire:
      enable: {{ .Values.agentsOperator.spireVars.SPIRE_ENABLED }}
      agent: {{ .Values.agentsOperator.spireVars.SPIRE_AGENT_URL }} 
{{- end }}