apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "kmux.name" . }}
  namespace: {{ .Values.namespace | default "accuknox-agents" }}
---  

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kmux.name" . }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kmux.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kmux.name" . }} 
subjects:
- kind: ServiceAccount
  name: {{ include "kmux.name" . }} 
  namespace: {{ .Values.namespace | default "accuknox-agents" }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kmux.name" . }}
  namespace: {{ .Values.namespace | default "accuknox-agents" }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kmux.name" . }}
  namespace: {{ .Values.namespace | default "accuknox-agents" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kmux.name" . }} 
subjects:
- kind: ServiceAccount
  name: {{ include "kmux.name" . }} 