namespace: accuknox-agents

ppsHost: ""

knoxGateway: ""

spireHost: ""

joinToken: ""

agentsOperator:
  
  tag: "v0.1.1"

  spireVars:
    SPIRE_AGENT_URL: "agents-operator.accuknox-agents.svc.cluster.local:9091"
    SPIRE_ENABLED: true

  resources: {}

  volumeMounts: []

  volumes: []


sharedInformerAgent: 
  
  tag: "v0.1.3"

  resources: {}

  volumeMounts: []

  volumes: []


policyEnforcementAgent: 
  
  tag: "v0.1.0"

  resources: {}

  volumeMounts: []

  volumes: []


feederService: 

  tag: "v0.1.4"

  resources: {}

  volumeMounts: []

  volumes: []

  discoveryEngineVars:
    DISCOVERYENGINE_ENABLED: "true"
    DISCOVERYENGINE_PORT: "9089"
    DISCOVERYENGINE_URL: "discovery-engine.accuknox-agents.svc.cluster.local"

  kubearmorVars:
    KUBEARMOR_URL: "kubearmor.kube-system.svc.cluster.local"
    KUBEARMOR_PORT: 32767
    KUBEARMOR_ALERTS: false
    KUBEARMOR_ENABLED: true
    KUBEARMOR_LOGS: "sdf"

  splunkVars:
    SPLUNK_FEEDER_ENABLED: "false"
    SPLUNK_FEEDER_URL: ""
    SPLUNK_FEEDER_TOKEN: ""
    SPLUNK_FEEDER_INDEX: ""
    SPLUNK_FEEDER_SOURCE: ""
    SPLUNK_FEEDER_SOURCE_TYPE: ""
    SPLUNK_ALERTS_ENABLED: "false"
    SPLUNK_LOGS_ENABLED: "false"

  azureSentinelVars:
    AZURE_SENTINEL_ENABLED: "false"
    AZURE_SENTINEL_LOGS_ENABLED: "false"
    AZURE_SENTINEL_ALERTS_ENABLED: "false"
    AZURE_SENTINEL_URL: ""
    AZURE_SENTINEL_GROUP_NAME: ""
    AZURE_SENTINEL_GROUP_VALUE: ""

discoveryEngine: 
  
  tag: "v0.10.0"

  resources: {}

  volumeMounts: []

  volumes: []

install:
  onlyFeeder: false
