{{- if eq .Values.config.secret_name "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "rafay-splunk.labels" . | nindent 4 }}
type: Opaque
data:
  rafaykey: {{ .Values.config.apikey | b64enc }}
  rafaysecret: {{ .Values.config.apisecret | b64enc }}
  token: {{ .Values.config.token | b64enc }}
{{- end -}}